framework:
    cache:
        pools:
            doctrine_result_cache_pool:
                adapter: cache.app
            doctrine_system_cache_pool:
                adapter: cache.system

        app: cache.adapter.apcu
