parameters:
    # Database
    database_host:     '%env(DB_HOST)%'
    database_port:     '%env(DB_PORT)%'
    database_name:     '%env(DB_NAME)%'
    database_user:     '%env(DB_USER)%'
    database_password: '%env(DB_PASSWORD)%'
    database_version:  '%env(DB_VERSION)%'
    database_driver:   '%env(DB_DRIVER)%'
    database_protocol: '%env(DB_PROTOCOL)%'
    database_charset:  '%env(DB_CHARSET)%'

services:
    result_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - method: setRedis
              arguments:
                    - '@redis'
    mem_cache:
        class: Doctrine\Common\Cache\ApcuCache

doctrine:
    dbal:
        driver:         '%database_driver%'
        url:            '%database_protocol%://%database_user%:%database_password%@%database_host%:%database_port%/%database_name%'
        server_version: '%database_version%'
        charset:        '%database_charset%'
        default_table_options:
            charset: '%database_charset%'
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        metadata_cache_driver:
            type: pool
            pool: doctrine_system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine_system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine_result_cache_pool
