# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    app_secret: '%env(APP_SECRET)%'
    cache_prefix_seed: '%env(REDIS_CACHE_PREFIX_SEED)%'

framework:
    secret: '%app_secret%'
    csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: '%cache_prefix_seed%'

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: 'redis://%redis_host%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
