###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.4"
services:

    redis:
        image: redis:5-alpine

    postgres:
        image: postgres:9.6-alpine
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=rss-proxy
        ports:
            - "7004:5432"

    webserver:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - .:/application
            - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./infrastructure/local/:/etc/ssl/local/
        ports:
            - "7000:443"

    php-fpm:
        build:
            dockerfile: Dockerfile
            target: backend-dev
            context: .
        working_dir: /application
        volumes:
            - .:/application
            - ./infrastructure/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    readability-js-server:
        image: phpdockerio/readability-js-server
        ports:
          - "7001:3000"
