###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: readability-rss-proxy-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: readability-rss-proxy-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=rss-proxy
      ports:
        - "7004:5432"

    webserver:
      image: nginx:alpine
      container_name: readability-rss-proxy-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: readability-rss-proxy-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

