# All routes are at the controller annotations
# Redirect root to feed admin
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin/feed
    permanent: true
